require 'prawn'
require 'prawn/table'

module Orders
  class OrderPdfGenerator
    def initialize(order)
      @order = order
      @supplier = order.supplier
      @location = order.location
      @organization = order.organization || order.user.current_organization
    end

    def generate
      Prawn::Document.new(page_size: 'LETTER', margin: 50) do |pdf|
        header(pdf)
        addresses(pdf)
        order_details(pdf)
        items_table(pdf)
        notes(pdf)
        footer(pdf)
      end.render
    end

    private

    def header(pdf)
      pdf.text "ORDER", size: 28, style: :bold, color: "333333"
      pdf.stroke_color "CCCCCC"
      pdf.stroke_horizontal_rule
      pdf.move_down 20
    end

    def addresses(pdf)
      pdf.text "From:", size: 10, style: :bold, color: "666666"
      pdf.text @organization.name, size: 14, style: :bold
      if @location
        pdf.text @location.name, size: 10 if @location.name != @organization.name
        pdf.text @location.address, size: 10 if @location.respond_to?(:address) && @location.address.present?
        pdf.text @location.phone, size: 10 if @location.respond_to?(:phone) && @location.phone.present?
      end
      pdf.text @order.user.email, size: 10

      pdf.move_down 15

      pdf.text "To:", size: 10, style: :bold, color: "666666"
      pdf.text @supplier.name, size: 14, style: :bold
      pdf.text @supplier.contact_email, size: 10

      pdf.move_down 20
    end

    def order_details(pdf)
      details = [
        ["Order Date:", @order.created_at.strftime('%B %d, %Y')],
        ["Requested Delivery:", @order.delivery_date&.strftime('%B %d, %Y') || 'Next available']
      ]
      details << ["Order #:", @order.confirmation_number] if @order.confirmation_number.present?

      details.each do |label, value|
        pdf.text "#{label} #{value}", size: 10
      end

      pdf.move_down 20
    end

    def items_table(pdf)
      data = [["Qty", "Item", "Unit Price", "Total"]]

      has_market_price = false

      @order.order_items.includes(:supplier_product).each do |item|
        product_name = item.supplier_product&.supplier_name || "Item"
        qty = format_quantity(item.quantity)

        if item.unit_price.present?
          data << [
            qty,
            product_name,
            format_price(item.unit_price),
            format_price(item.line_total)
          ]
        else
          has_market_price = true
          data << [
            qty,
            product_name,
            "Market Price",
            "*"
          ]
        end
      end

      # Total row
      data << ["", "", "Estimated Total:", format_price(@order.calculated_subtotal)]

      pdf.table(data, width: pdf.bounds.width, cell_style: { size: 9, padding: [6, 8] }) do |table|
        table.row(0).font_style = :bold
        table.row(0).background_color = "F5F5F5"
        table.row(-1).font_style = :bold
        table.row(-1).border_top_width = 2

        # Column widths and alignment
        table.column(0).width = 50
        table.column(2).align = :right
        table.column(3).align = :right
        table.column(2).width = 100
        table.column(3).width = 100
      end

      if has_market_price
        pdf.move_down 5
        pdf.text "* Items at market price not included in total.", size: 8, color: "999999"
      end
    end

    def notes(pdf)
      return unless @order.notes.present?
      pdf.move_down 20
      pdf.text "Notes:", size: 10, style: :bold
      pdf.text @order.notes, size: 10

      if @supplier.ordering_instructions.present?
        pdf.move_down 10
        pdf.text "Supplier Notes:", size: 10, style: :bold, color: "666666"
        pdf.text @supplier.ordering_instructions, size: 10, color: "666666"
      end
    end

    def footer(pdf)
      pdf.move_down 30
      pdf.stroke_color "CCCCCC"
      pdf.stroke_horizontal_rule
      pdf.move_down 10
      pdf.text "Generated by EnPlace Pro", size: 8, color: "999999"
    end

    def format_price(amount)
      return "—" unless amount
      "$#{'%.2f' % amount}"
    end

    def format_quantity(qty)
      return qty.to_s unless qty
      qty == qty.to_i ? qty.to_i.to_s : qty.to_s
    end
  end
end
